---
apiVersion: v2
appVersion: 2023.11.3
description: Home Assistant
name: home-assistant
version: 14.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - home-assistant
  - hass
  - homeassistant
home: https://github.com/damacus/charts/tree/main/charts/application/home-assistant
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
sources:
  - https://github.com/home-assistant/home-assistant
  - https://github.com/cdr/code-server
  - https://github.com/damacus/charts/tree/main/charts/stable/home-assistant
maintainers:
  - name: damacus
    email: dan.webb@damacus.io
dependencies:
  - name: common
    repository: https://damacus.github.io/charts
    version: 5.0.1
  - name: postgresql
    version: 13.2.23
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 14.1.4
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: influxdb
    version: 5.10.2
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 5.0.1
